(()=>{"use strict";
const FULL_IDS=["practice-mode-btn","load-save-btn","tickets-mode-btn","backup-mode-btn","monitor-mode-btn","docs-mode-btn","workshop-mode-btn"];
const labels={practice:"Praticar",load:"Carregar Save",tickets:"Central de Chamados",backup:"Backup & Deploy",monitor:"Monitoramento",docs:"Meus Documentos",workshop:"Montar a Oficina"};
function lockButton(id){const b=document.getElementById(id);if(!b)return;b.dataset.demoLocked="1";b.classList.add("demo-locked");const em=b.querySelector("em");if(em)em.textContent="VERSÃO COMPLETA";b.title="Disponível na versão completa do ResolveTech";}
function notice(title="Recurso da versão completa"){let m=document.getElementById("demo-lock-modal");if(!m){m=document.createElement("div");m.id="demo-lock-modal";m.className="demo-lock-modal hidden";m.innerHTML='<div class="demo-lock-card"><div class="badge">RESOLVETECH DEMO</div><h2></h2><p></p><div class="demo-lock-actions"><button class="secondary" id="demo-lock-close">Continuar na demo</button><a class="primary demo-link" href="/MeusProjetos/projetos/resolvetech/">Conhecer o projeto</a></div></div>';document.body.appendChild(m);m.querySelector("#demo-lock-close").onclick=()=>m.classList.add("hidden");}m.querySelector("h2").textContent=title;m.querySelector("p").textContent="Esta demonstração libera a Biblioteca, a Oficina de Upgrade e os três primeiros níveis do Modo História. Os demais recursos permanecem disponíveis na versão completa.";m.classList.remove("hidden");}
function finishDemo(){document.querySelectorAll(".screen.active").forEach(x=>x.classList.remove("active"));let s=document.getElementById("demo-finish-screen");if(!s){s=document.createElement("section");s.id="demo-finish-screen";s.className="screen active hero-screen";s.innerHTML='<div class="panel final-panel"><div class="badge">DEMONSTRAÇÃO CONCLUÍDA</div><h2>Você concluiu os 3 níveis da demo</h2><p>Você experimentou uma parte do Modo História do ResolveTech. A versão completa continua com novos atendimentos, conteúdos e ferramentas.</p><div class="learning-box"><strong>A demo continua aberta:</strong> você ainda pode explorar a Biblioteca, experimentar a Oficina de Upgrade ou repetir os níveis em outra dificuldade.</div><div class="demo-finish-actions"><button class="primary" id="demo-home">Voltar ao ResolveTech</button><a class="secondary demo-link" href="/MeusProjetos/projetos/resolvetech/">Conhecer o projeto</a></div></div>';document.querySelector("main").appendChild(s);s.querySelector("#demo-home").onclick=()=>{location.reload()};}else s.classList.add("active");window.scrollTo({top:0,behavior:"smooth"});}
function levelFromPage(){const active=[...document.querySelectorAll(".screen.active")];const text=active.map(x=>x.innerText||"").join(" ");const m=text.match(/N[ÍI]VEL\s*(\d+)/i);return m?Number(m[1]):null;}
let blocking=false;
function enforce(){if(blocking)return;const n=levelFromPage();if(n&&n>3){blocking=true;finishDemo();setTimeout(()=>blocking=false,250);}}
document.addEventListener("click",e=>{const b=e.target.closest("[data-demo-locked='1']");if(b){e.preventDefault();e.stopImmediatePropagation();notice();}},true);
document.addEventListener("DOMContentLoaded",()=>{FULL_IDS.forEach(lockButton);const badge=document.createElement("div");badge.className="demo-ribbon";badge.textContent="DEMONSTRAÇÃO · HISTÓRIA NÍVEIS 1–3";document.body.appendChild(badge);new MutationObserver(enforce).observe(document.body,{subtree:true,attributes:true,attributeFilter:["class"],childList:true,characterData:true});setInterval(enforce,500);});
})();